### ISSUE TITLE
App doesn't show up in Flathub

### ISSUE THREAD

**Issue by jsparber** [flathub/org.gnome.NautilusPreviewer#5]
https://flathub.org/apps/details/org.gnome.NautilusPreviewer returns app not found.

**Comment by fedelibre** [comment]
I've reported it somewhere some time ago and I was told that it is intentional, since this is an extension of Nautilus.

**Comment by jsparber** [comment]
Yeah that makes sense it's marked as an addon in appstream, would be nice to have addons show up in the app store though.
